services:
  php-base:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./working_laravel:/var/www/html
      - /var/www/html/vendor
      - /var/www/html/node_modules
    env_file:
      - "./docker/webapp.env"
      - "./working_laravel/.env"
    networks:
      - boilerplate_network

  web:
    container_name: web
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    depends_on:
      - php
      - mysql
    volumes:
      - ./working_laravel/public:/var/www/html/public
      - ./working_laravel/storage/app/public:/var/www/html/storage/app/public
    networks:
      - boilerplate_network
    ports:
      - ${WEB_PORT:-80}:80
      - ${WEB_PORT_SECURE:-443}:443
    env_file:
      - "./docker/webapp.env"
      - "./working_laravel/.env"

  php:
    extends:
      service: php-base
    container_name: php
    depends_on:
      - mysql
    ports:
      - ${PHP_PORT:-9000}:9000

  composer:
    extends:
      service: php-base
    container_name: composer
    entrypoint: [ "composer" ]

  artisan:
    extends:
      service: php-base
    container_name: artisan
    entrypoint: [ "php", "artisan" ]

  mysql:
    container_name: mysql
    image: mariadb:10.6
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - ${MYSQL_PORT:-3306}:3306
    networks:
      - boilerplate_network
    env_file:
      - "./docker/webapp.env"
      - "./working_laravel/.env"

  npm:
    container_name: npm
    image: node:lts-alpine
    working_dir: /var/www/html
    volumes:
      - ./working_laravel:/var/www/html
      - /var/www/html/node_modules
    entrypoint: [ 'npm' ]
    networks:
      - boilerplate_network
    env_file:
      - "./docker/webapp.env"
      - "./working_laravel/.env"

networks:
  boilerplate_network:
    driver: bridge

volumes:
  db_data:
    driver: 'local'
