services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    volumes:
      - ./working_laravel/public:/var/www/html/public
    networks:
      - app-network
    ports:
      - ${WEB_PORT:-80}:80
      - ${WEB_PORT_SECURE:-443}:443
    env_file:
      - "./docker/webapp.env"

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
    driver: 'local'
